CREATE TABLE
    PERSONAS (
        id INTEGER PRIMARY KEY,
        RUT NUMBER (8),
        NOMBRES VARCHAR (64),
        APELLIDO VARCHAR (64),
        FECHA_NACIMIENTO DATE
    ); 

CREATE TABLE
    PARTICIPANTE (
        id INTEGER PRIMARY KEY,
        NOMBRE VARCHAR (64),
        APELLIDO VARCHAR (64),
        EDAD NUMBER (100),
        NUMERO_INSCRIPCION NUMBER (100)
    );

CREATE TABLE 
    ATLETA (
    id INTEGER PRIMARY KEY,
    NOMBRE VARCHAR (64),
    APELLIDO VARCHAR (64),
    EDAD NUMBER (100),
    MARCA VARCHAR (100),
    EQUIPO VARCHAR (100),
    PLAN_ENTRENO NUMBER (20)
    );

CREATE TABLE
    ENTRENADOR (
    id INTEGER PRIMARY KEY,
    NOMBRE VARCHAR (64),
    APELLIDO VARCHAR (64),
    EDAD NUMBER (100),
    EQUIPO VARCHAR (100),
    PLAN_ENTRENO NUMBER (20)
    );

CREATE TABLE 
    JUEZ (
    id INTEGER PRIMARY KEY,
    NOMBRE VARCHAR (64),
    APELLIDO VARCHAR (64),
    EDAD NUMBER (100),
    ESPECIALIDAD VARCHAR (100),
    REGLAMENTO NUMBER (50)
    );